// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgYARTUQzL-N2fhBrFpccTNe4BxSeA1c',
    appId: '1:1066315564308:web:7692363423f097b69eae01',
    messagingSenderId: '1066315564308',
    projectId: 'notifications-e44ce',
    authDomain: 'notifications-e44ce.firebaseapp.com',
    storageBucket: 'notifications-e44ce.firebasestorage.app',
    measurementId: 'G-GYLM6YMBS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ib8RzohBb2AdJ6Bv3_ZiMFb4RRo-Vfg',
    appId: '1:1066315564308:android:83bebd2263d05aed9eae01',
    messagingSenderId: '1066315564308',
    projectId: 'notifications-e44ce',
    storageBucket: 'notifications-e44ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrUnRJuow0g-tyP29RxPQJkNUZx08Sj1U',
    appId: '1:1066315564308:ios:8cc1ff7d9aaf4c859eae01',
    messagingSenderId: '1066315564308',
    projectId: 'notifications-e44ce',
    storageBucket: 'notifications-e44ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9Klitou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrUnRJuow0g-tyP29RxPQJkNUZx08Sj1U',
    appId: '1:1066315564308:ios:8cc1ff7d9aaf4c859eae01',
    messagingSenderId: '1066315564308',
    projectId: 'notifications-e44ce',
    storageBucket: 'notifications-e44ce.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9Klitou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzgYARTUQzL-N2fhBrFpccTNe4BxSeA1c',
    appId: '1:1066315564308:web:07f288f636848f3a9eae01',
    messagingSenderId: '1066315564308',
    projectId: 'notifications-e44ce',
    authDomain: 'notifications-e44ce.firebaseapp.com',
    storageBucket: 'notifications-e44ce.firebasestorage.app',
    measurementId: 'G-FE0KGQ3Q7X',
  );
}
